### ISSUE TITLE
How load by default index.html

### ISSUE THREAD

**Issue by paulvanbladel** [nathanaw/generator-aurelia-vs2015#3]
How do you make sure that the index.html file is loaded by default when browsing to:
http://localhost:12356

The blog post is suggesting that F5 does start the index.html, but that's not happing on my machine :)
cheers
paul.

**Comment by paulvanbladel** [comment]
ok, that's easy.
In startup configuration
 app.UseDefaultFiles();
 app.UseStaticFiles();

**Comment by nathanaw** [comment]
Which asp.net template dud you select? Empty, webapi, or mvc? I had this issue when I selected Empty.
